version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - docker-compose -f ./.build/docker-compose.yml up -d
      - docker-compose -f ./build/docker-compose.yml exec -T php-fpm composer install
      - docker-compose -f ./build/docker-compose.yml exec php-fpm vendor/bin/pimcore-install --mysql-host-socket=db --mysql-username=pimcore --mysql-password=pimcore --mysql-database=pimcore

  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
