version: 0.2

phases:
  build:
    commands:
      - echo starting docker containers and setting them up
      - docker-compose -f ./.build/docker-compose.yml up -d
      - docker-compose -f ./.build/docker-compose.yml exec -T php-fpm composer install
      - docker-compose -f ./.build/docker-compose.yml exec -T -e PIMCORE_INSTALL_ADMIN_USERNAME=pimcore -e PIMCORE_INSTALL_ADMIN_PASSWORD=pimcore -e PIMCORE_INSTALL_MYSQL_USERNAME=pimcore -e PIMCORE_INSTALL_MYSQL_PASSWORD=pimcore php-fpm vendor/bin/pimcore-install -n --mysql-host-socket=db --mysql-database=pimcore
      - docker-compose -f ./.build/docker-compose.yml exec -T php-fpm pimcore:deployment:classes-rebuild -c -v  
