doctrine:
    dbal: { connections: { default: { host: db, port: 3306, user: root, password: ROOT, dbname: pimcore, mapping_types: { enum: string, bit: boolean }, server_version: mariadb-10.5.12 } } }
